name: Preview Build

on:
  push:
    branches:
      - preview

jobs:
  test:
    uses: ./.github/workflows/test.yml

  preview:
    needs: test
    name: Create Preview Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          
      - name: Install dependencies
        run: npm ci

      - name: Install webview-ui dependencies
        run: cd webview-ui && npm ci
        
      - name: Set Preview Version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          GIT_HASH=$(git rev-parse --short HEAD)
          DATE=$(date +%Y%m%d)
          echo "RELEASE_VERSION=${VERSION}-${GIT_HASH}-${DATE}" >> $GITHUB_ENV
          npm version $RELEASE_VERSION --no-git-tag-version
        
      - name: Build VSIX
        run: |
          npm run package
          npm run vscode:package
          
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VSIX_PATH=$(find . -name "*.vsix")
          gh release create "v$RELEASE_VERSION" \
            --prerelease \
            --title "Preview v$RELEASE_VERSION" \
            --notes "Preview build from preview branch" \
            "$VSIX_PATH"
